OCR/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

from accounts.views import (
    login_view,
    logout_view,
    register_view
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('pdf_gen.urls')),
    path('invoice/', include('api.urls')),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]
if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

api/urls.py
from django.urls import path, include
from .views import *

app_name='invoices'

urlpatterns = [
    path('invoice_list_view/', invoice_list_view,name='list'),
    path('create/', invoice_create_view,name='create'),
    path("<int:id>/edit/", invoice_update_view, name='update'),
    path('invoice-delete/<int:id>', delete_invoice, name="invoice-delete"),

]

templates/invoices/create-update.html
{% extends "base.html" %} 


{% block breadcrumb %}

   <li class="breadcrumb-item "><a href="{% url 'home' %}">home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'invoices:list' %}">Invoice List</a></li>
        <li class="breadcrumb-item active">Invoice Detail</li>
{%endblock%}
{% block content %}
<style>
  .ingredient-form {
    border-bottom: 1px solid black;
  }
  .hidden {
    display: none;
  }
  .errorlist {
    color:red;
    size:1rem;
    transform:translateX(-30px)
  }

</style>

 {% include 'partials/form-htmx.html' %}
  
 <script>
  const addMoreBtn = document.getElementById("add-more");
  const totalNewForms = document.getElementById("id_form-TOTAL_FORMS");
  const delBtn = document.getElementById("delete-btn");
  addMoreBtn.addEventListener("click", add_new_form);
  const saveButton = document.getElementById("save-here")
  saveButton.addEventListener("click", hide);

  function add_new_form(event) {
    console.log("clicked");
    if (event) {
      event.preventDefault();
    }

    const currentIngredientForms =
      document.getElementsByClassName("ingredient-form");
    const currentFormCount = currentIngredientForms.length; // + 1
    const formCopyTarget = document.getElementById("ingredient-form-list");
    const copyEmptyFormEl = document
      .getElementById("empty-form")
      .cloneNode(true);
    copyEmptyFormEl.setAttribute("class", "ingredient-form");
    copyEmptyFormEl.setAttribute("id", `form-${currentFormCount}`);
    const regex = new RegExp("__prefix__", "g");
    copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(
      regex,
      currentFormCount
    );
    console.log(copyEmptyFormEl, ' opy')
    totalNewForms.setAttribute("value", currentFormCount + 1);
    // now add new empty form element to our html form
    formCopyTarget.append(copyEmptyFormEl);
  }

  {% comment %} setTimeout( {% endcomment %}
  async function hide(event) {
    if (event) {
      event.preventDefault
    }
    const modal = document.getElementById("error-modal");
    // hide modal after 3 seconds
    console.log('start timer');
    await new Promise(resolve => setTimeout(resolve, 2000));
    console.log(' 2 waiting')
    modal.style.display = "none";
}
{% comment %} , 2800); {% endcomment %}
</script> 

{% endblock content %}

templates/invoices/invoice_list.html
{% extends 'base.html' %}

{%block title%}Invoice List {%endblock%}

{% block breadcrumb %}

   <li class="breadcrumb-item "><a href="{% url 'home' %}">home</a></li>
        <li class="breadcrumb-item active">Invoice List</li>
{%endblock%}

{% block content %}
<div style='margin-left:10px;display:flex' style=''>
            <div style="width:50%" class="input-group">
        <form>
                <input  name="q" type="text" placeholder="Search" class="form-control form-control-lg" />
                <div style='padding:4px' class="input-group-append">
                    <button style='background-color:grey; ' class="btn btn-primary btn-lg">Search</button>
                </div>
        </form> 
            </div>
        <div style='justify-content:flex-end'>
        <form method="post" enctype="multipart/form-data" class="dropzone">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class='custom-btn' href="{% url 'home' %}" style="width:100%; margin-top:10%;" type="submit"
                    class="btn btn-primary btn-lg-5">Upload</button>
            </form>
            </div>
</div>

    <div class="col-lg-12">
      {% include "partials/messages.html"%}
    </div>
<div class="row">

<div class='tables' style='margin:30px;height:25vw;width:80vw; border:1px solid black;border-right:1px solid black;'>    
<table class="ui red table" style=''>
    <thead>
      <tr>
        <th >Ref</th>
        <th >invoice date</th>
        <th >total_invoice_amount</th>
        <th >Actions</th>
      </tr>
    </thead>
    <tbody>
        {% for invoice in page.object_list %}

      <tr >
        <td>
        {% if invoice.get_absolute_url %}<small><a href='{{ invoice.get_absolute_url }}'>{{invoice.inv_ref}}</a></small>{% endif %}</h1>
            
        </td>
        <td>{{ invoice.invoice_date }}</td>
        <td>{{ invoice.total_invoice_amount }}</td>
        <td >
            <div class="col-md-2">
      <a
        href="{% url 'invoices:invoice-delete' invoice.id %}"
        class="btn btn-danger btn-sm"
        >Delete</a
      >
    </div>
    </td>
      </tr>

      {% endfor %}
    </tbody>
  </table>
  </div>

  <div class="page-links" style ="position:absolute;">
    <div class="ui borderless menu" style="height: 50px;">
       
    {% if page.has_previous %}
    <a style="margin-right: 5%; background-color:#1e6de3; color: white;"class="item" href="{% url 'all_cards' %}?page=1"> First <br> <i class="angle double left icon"></i> </a>
    <a style=" margin-right: 5%; background-color:#1e6de3; color: white;" class="item" href="{% url 'all_cards' %}?page={{ page.previous_page_number }}"> Previous<i class="angle left icon"></i> </a>
    {% endif %}
    {% if page.has_next %}
    <a style=" margin-right: 5%; background-color:#1e6de3; color: white;" class="item" href="{% url 'all_cards' %}?page={{ page.next_page_number }}"> Next<i class="angle right icon"></i> </a>
    <a style="background-color:#1e6de3; color: white;" class="item" href="{% url 'all_cards' %}?page={{ num_pages }}"> Last <i class="angle double right icon"></i> </a>
    {% endif %}
    </div>
  </div>

  <div class="page-links" style ="position:absolute;">
    <div class="ui borderless menu" style="height: 50px;">
       
    {% if page.has_previous %}
    <a style="margin-right: 5%; background-color:#1e6de3; color: white;"class="item" href="{% url 'all_cards' %}?page=1"> First <br> <i class="angle double left icon"></i> </a>
    <a style=" margin-right: 5%; background-color:#1e6de3; color: white;" class="item" href="{% url 'all_cards' %}?page={{ page.previous_page_number }}"> Previous<i class="angle left icon"></i> </a>
    {% endif %}
    {% if page.has_next %}
    <a style=" margin-right: 5%; background-color:#1e6de3; color: white;" class="item" href="{% url 'all_cards' %}?page={{ page.next_page_number }}"> Next<i class="angle right icon"></i> </a>
    <a style="background-color:#1e6de3; color: white;" class="item" href="{% url 'all_cards' %}?page={{ num_pages }}"> Last <i class="angle double right icon"></i> </a>
    {% endif %}
    </div>
  </div>

  

</div>

{% endblock %}